In [1]:
import pandas as pd

## Input and view data training

In [2]:
df = pd.read_csv('C:\\Users\\ASUS\\Documents\\Machine Learning\\ml\\data_training4.csv')
df

,Universitas,Jenis_Program_Studi,Kualitas_Dosen,Kepuasan_Infrastruktur,Keluhan_Fisik,Kendala_Online,Performa_Akademik,Keluhan_Psikis,Kepuasan_Online
0,Universitas Internasional Batam,Non Computing & Non Engineering,3,3,Sering Mengantuk,Tidak Ada Kendala / Tidak Ada Diatas,4,Bosan;Stress;Tidak Ada Keluhan / Tidak Ada Diatas,3
1,Universitas Internasional Batam,Computing & Engineering,4,3,Tidak Ada Keluhan / Tidak Ada Diatas,Tidak Ada Kendala / Tidak Ada Diatas,5,Tidak Ada Keluhan / Tidak Ada Diatas,4
2,Politeknik Negeri Batam,Computing & Engineering,2,4,Badan Pegal,Tidak Ada Kendala / Tidak Ada Diatas,1,Patah Hati,1
3,Universitas Universal,Computing & Engineering,3,3,Kelelahan Mata,Kendala Internet,3,Bosan,3
4,Universitas Putera Batam,Computing & Engineering,1,1,Sering Mengantuk,Kendala Internet,4,Cemas,2
...,...,...,...,...,...,...,...,...,...
316,Universitas Putera Batam,Computing & Engineering,3,3,Tidak Ada Keluhan / Tidak Ada Diatas,Tidak Ada Kendala / Tidak Ada Diatas,3,Tidak Ada Keluhan / Tidak Ada Diatas,3
317,Universitas Putera Batam,Computing & Engineering,3,3,Kelelahan Mata,Kendala Internet,3,Tidak Ada Keluhan / Tidak Ada Diatas,3
318,Universitas Putera Batam,Computing & Engineering,3,3,Tidak Ada Keluhan / Tidak Ada Diatas,Tidak Ada Kendala / Tidak Ada Diatas,3,Tidak Ada Keluhan / Tidak Ada Diatas,3
319,Universitas Putera Batam,Computing & Engineering,3,3,Tidak Ada Keluhan / Tidak Ada Diatas,Kendala Internet,3,Tidak Ada Keluhan / Tidak Ada Diatas,3
320,Universitas Putera Batam,Computing & Engineering,3,3,Tidak Ada Keluhan / Tidak Ada Diatas,Kendala Internet,3,Bosan,3

## Data Preprocessing

In [3]:
from sklearn import preprocessing
def label_array(array) :
    encoder = preprocessing.LabelEncoder()
    encoder.fit(array.unique())
    encoded_value = encoder.transform(array)
    return encoded_value

In [4]:
X1 = pd.DataFrame({"":label_array(df['Universitas'],)})
X2 = pd.DataFrame({"":label_array(df['Jenis_Program_Studi'],)})
X3 = pd.DataFrame({"":label_array(df['Keluhan_Fisik'],)})
X4 = pd.DataFrame({"":label_array(df['Kendala_Online'],)})
X5 = pd.DataFrame({"":label_array(df['Keluhan_Psikis'],)})

print("")
print(X1.to_string(index=False, header=False))

print("")
print(X2.to_string(index=False, header=False))

print("")
print(X3.to_string(index=False, header=False))

print("")
print(X4.to_string(index=False, header=False))

print("")
print(X5.to_string(index=False, header=False))

2
2
1
4
3
2
2
0
1
4
2
2
2
2
1
3
2
3
2
3
2
2
3
0
2
3
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
3
3
3
3
3
3
3
3
3
3
2
2
2
3
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
4
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
3
3
3
3
2
3
3
3
3
3
2
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
2
2
3
3
3
3
3
3
3
3
3
3
3

1
0
0
0
0
0
1
0
0
1
1
0
0
1
1
1
1
1
0
0
0
1
1
0
1
1
0
1
1
1
1
1
1
1
1
1
1
0
1
1
0
1
1
1
0
1
1
1
1
1
1
1
0
1
1
1
0
1
1
0
0
1
0
1
0
1
1
1
1
1
1
1
1
1
1
1
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0
1
0
0
0
0
0
0
0
1
1
1
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0
1
1
1
1
1
1
1
1
1
1
1
0
0
0
0
1
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

3
5
0
1
3
2
1
5
1
1
1
3
5
5
6
1
5
6
5
4
4
1
5
1
1
5
1
1
3
2
1
0
2
1
1
5
1
5
6
5
5
5
5
5
5
3
5
5
5
5
5
5
5
5
5
2
1
5
2
5
5
1
1
1
4
5
1
5
5
5
5
5
5
5
5
5
1
0
2
2
5
3
5
5
1
3
5
5
5
5
3
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
1
5
5
5
5
5
5
3
1
2
1
2
5
5
5
3
5
5
5
1
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
1
5
5
5
5
5
1
5
5
1
5
5
5

6
6
6
0
0
4
0
6
3
2
0
0
6
6
6
0
4
3
4
5
4
0
6
6
0
6
6
0
1
6
0
0
6
0
6
6
0
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
0
6
6
6
0
6
6
6
0
6
6
6
6
6
6
6
6
0
6
6
0
6
1
6
6
0
6
6
6
0
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
0
4
3
0
5
6
0
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
6
0
6
6
6
6
0
6
6
6
0
6
0
0

2
8
6
0
3
3
3
0
3
0
0
0
8
8
0
8
8
3
8
0
3
0
8
5
0
8
0
0
0
5
0
0
5
0
8
8
0
8
8
8
8
8
8
8
8
8
8
5
5
8
8
5
8
8
8
1
8
0
5
8
0
8
8
5
0
5
8
8
8
8
8
8
5
0
8
8
0
8
3
0
8
0
5
8
8
8
8
8
8
8
8
8
5
8
8
5
8
8
0
8
0
8
8
8
8
8
8
8
8
8
8
0
8
0
7
5
4
3
8
8
8
4
8
8
8
5
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
0
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
5
8
8
8
8
8
8
8
8
8
8
8
8
8
5
5
5
5
5
5
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
5
5
5
8
8
8
8
8
8
8
8
8
8
8
8
8
5
5
5
8
8
8
8
8
5
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
8
5
8
8
8
5
8
8
8
5
8
8
8
8
8
0
8
8
0
8
8
0
3
8
0
8
0
0
8
8
8
8
8
8
0

In [5]:
y = df['Kepuasan_Online']
print(y.to_string(index=False, header=False))

3
4
1
3
2
3
4
1
4
2
4
4
5
5
4
4
5
5
5
5
5
4
5
4
3
4
3
3
2
2
4
3
2
3
3
3
3
3
4
4
5
4
3
3
3
3
3
3
3
3
3
3
3
3
3
2
3
3
3
3
3
5
3
5
4
3
4
4
4
3
3
3
5
5
4
4
3
4
3
3
5
3
3
3
3
5
5
4
5
4
4
5
4
5
4
4
5
5
5
5
5
5
5
5
4
4
4
5
5
4
4
4
4
3
4
4
4
4
4
4
4
1
4
3
4
3
3
3
3
3
3
4
4
3
3
3
3
3
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
3
3
3
5
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
3
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
3
3
3
3
3
3
3
3
3
3
3
3
4
4
4
3
3
3
3
3
3
3
3
3

In [6]:
pp_df = pd.concat([X1, X2, X3, X4, X5], axis=1)
pp_df.columns = ['Universitas', 'Jenis_Program_Studi', 'Keluhan_Fisik', 'Kendala_Online', 'Keluhan_Psikis']
pp_df.insert(0, "Model", "Random Forest Classifier")
pp_df = pp_df.drop('Model', axis=1)
pp_df

,Universitas,Jenis_Program_Studi,Keluhan_Fisik,Kendala_Online,Keluhan_Psikis
0,2,1,3,6,2
1,2,0,5,6,8
2,1,0,0,6,6
3,4,0,1,0,0
4,3,0,3,0,3
...,...,...,...,...,...
316,3,0,5,6,8
317,3,0,1,0,8
318,3,0,5,6,8
319,3,0,5,0,8
320,3,0,5,0,0

In [7]:
new_data = pd.read_csv('data_training4.csv')

In [8]:
new_df1 = df['Kualitas_Dosen'].values
new_df2 = df['Kepuasan_Infrastruktur'].values
new_df3 = df['Performa_Akademik'].values

In [9]:
new_df = pd.DataFrame({
    'Kualitas_Dosen': new_df1 , 
    'Tingkat_Infrastruktur': new_df2,
    'Performa_Akademik': new_df3 
})

new_df

     Kualitas_Dosen  Tingkat_Infrastruktur  Performa_Akademik
0                 3                      3                  4
1                 4                      3                  5
2                 2                      4                  1
3                 3                      3                  3
4                 1                      1                  4
..              ...                    ...                ...
316               3                      3                  3
317               3                      3                  3
318               3                      3                  3
319               3                      3                  3
320               3                      3                  3

[321 rows x 3 columns]

In [10]:
df = pd.concat([pp_df, new_df], axis=1)

In [11]:
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.5, random_state=100)

In [12]:
X_train

,Universitas,Jenis_Program_Studi,Keluhan_Fisik,Kendala_Online,Keluhan_Psikis,Kualitas_Dosen,Tingkat_Infrastruktur,Performa_Akademik
82,2,1,5,6,5,3,3,3
156,2,1,5,6,8,4,4,4
203,2,1,5,6,8,4,4,4
217,2,1,5,6,5,4,4,4
74,2,1,5,6,8,3,4,4
...,...,...,...,...,...,...,...,...
66,2,1,1,6,8,4,3,4
53,2,1,5,6,8,3,3,3
79,2,0,2,6,0,5,5,4
280,3,0,5,6,8,4,4,4
8,1,0,1,3,3,4,4,4

In [13]:
X_test
y_train

82     3
156    4
203    4
217    4
74     4
      ..
66     4
53     3
79     3
280    4
8      4
Name: Kepuasan_Online, Length: 160, dtype: int64

# Modeling

### Random Forest Classifier

In [14]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)

RandomForestClassifier()

## Training the model

In [15]:
y_rfc_train_pred = rfc.predict(X_train)
y_rfc_test_pred = rfc.predict(X_test)

In [16]:
y_rfc_train_pred

array([3, 4, 4, 4, 4, 4, 3, 3, 4, 4, 3, 2, 3, 4, 4, 4, 4, 3, 3, 4, 4, 3,
       4, 4, 3, 4, 4, 4, 5, 4, 3, 3, 3, 4, 4, 3, 4, 4, 4, 3, 4, 5, 4, 4,
       3, 5, 5, 3, 4, 4, 3, 4, 4, 4, 3, 1, 4, 3, 5, 4, 4, 4, 4, 3, 4, 4,
       4, 4, 4, 4, 2, 4, 3, 4, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 3, 3, 3,
       4, 4, 4, 4, 3, 4, 3, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 3, 3, 4, 4,
       3, 4, 4, 3, 5, 4, 4, 5, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 4, 1, 4,
       4, 4, 4, 3, 3, 4, 2, 5, 4, 4, 4, 4, 5, 4, 3, 3, 4, 4, 3, 4, 4, 4,
       4, 4, 3, 3, 4, 4], dtype=int64)

In [17]:
y_rfc_test_pred

array([4, 3, 4, 4, 4, 5, 3, 4, 3, 4, 4, 4, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4,
       3, 4, 3, 4, 3, 4, 4, 3, 3, 3, 4, 5, 3, 4, 4, 4, 4, 4, 4, 4, 5, 3,
       4, 3, 3, 3, 4, 3, 4, 5, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 4, 4, 3,
       4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 5, 4, 3, 4, 4, 3, 4, 4, 3, 4, 3, 4,
       4, 4, 4, 5, 4, 3, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 5, 3, 4, 4, 3,
       3, 4, 4, 4, 3, 4, 4, 4, 3, 4, 4, 3, 4, 4, 3, 3, 5, 5, 4, 4, 4, 3,
       3, 4, 5, 4, 4, 3, 4, 3, 3, 4, 4, 3, 5, 4, 3, 4, 4, 4, 4, 3, 4, 5,
       4, 4, 3, 3, 3, 4, 4], dtype=int64)

## Evaluasi Model

In [18]:
#Input Model
from sklearn.metrics import accuracy_score, precision_score

rfc_train_accuracy = accuracy_score(y_train, y_rfc_train_pred)
rfc_test_accuracy = accuracy_score(y_test, y_rfc_test_pred)

rfc_train_precision = precision_score(y_train, y_rfc_train_pred, average='weighted', zero_division=0)
rfc_test_precision = precision_score(y_test, y_rfc_test_pred, average='weighted', zero_division=0)

print('Train Accuracy:', rfc_train_accuracy)
print('Test Accuracy:', rfc_test_accuracy)
print('Train Precision:', rfc_train_precision)
print('Test Precision:', rfc_test_precision)

Train Accuracy: 0.975
Test Accuracy: 0.8881987577639752
Train Precision: 0.9757451923076923
Test Precision: 0.8659608154084947

In [19]:
rfc_result = pd.DataFrame(('Random Forest Classifier', rfc_train_accuracy, rfc_test_accuracy, rfc_train_precision, rfc_test_precision)).transpose()
rfc_result.columns = ['Model', 'Accuracy Train', 'Accuracy Test', 'Precision Train', 'Precision Test']
rfc_result

,Model,Accuracy Train,Accuracy Test,Precision Train,Precision Test
0,Random Forest Classifier,0.975,0.888199,0.975745,0.865961

## Save the model

In [20]:
import sklearn
import joblib

joblib.dump(rfc,"RFC(1.0.2).pkl")

['RFC(1.0.2).pkl']