In [1]:
import pandas as pd

## Input and view data training

In [2]:
df = pd.read_csv('C:\\Users\\ASUS\\Documents\\Machine Learning\\ml\\data_training.csv')
df

,Universitas,Jenis Program Studi,Kualitas Dosen\n\n(Selama Pembelajaran Online),Tingkat Kepuasan Terhadap Infrastruktur Online,Keluhan Fisik Selama Pembelajaran Online,Kendala Selama Pembelajaran Online,Performa Akademik Selama Pembelajaran Online,Keluhan Psikis Selama Pembelajaran Online,Kepuasan Terhadap Pembelajaran Online
0,Universitas Internasional Batam,Non Computing & Non Engineering,3,3,Sering Mengantuk,Tidak Ada Kendala / Tidak Ada Diatas,4,Bosan;Stress;Tidak Ada Keluhan / Tidak Ada Diatas,3
1,Universitas Internasional Batam,Computing & Engineering,4,3,Tidak Ada Keluhan / Tidak Ada Diatas,Tidak Ada Kendala / Tidak Ada Diatas,5,Tidak Ada Keluhan / Tidak Ada Diatas,4
2,Politeknik Negeri Batam,Computing & Engineering,2,4,Badan Pegal,Tidak Ada Kendala / Tidak Ada Diatas,1,Patah Hati,1
3,Universitas Universal,Computing & Engineering,3,3,Kelelahan Mata;Sering Mengantuk;Badan Pegal,Kendala Internet,3,Bosan;Stress;Cemas;Depresi,3
4,Universitas Putera Batam,Computing & Engineering,1,1,Sering Mengantuk;Badan Pegal;Sulit Istirahat,Kendala Internet;Kendala Perangkat,4,Cemas,2
...,...,...,...,...,...,...,...,...,...
108,Universitas Internasional Batam,Non Computing & Non Engineering,4,5,Tidak Ada Keluhan / Tidak Ada Diatas,Tidak Ada Kendala / Tidak Ada Diatas,5,Tidak Ada Keluhan / Tidak Ada Diatas,5
109,Universitas Internasional Batam,Computing & Engineering,4,4,Tidak Ada Keluhan / Tidak Ada Diatas,Tidak Ada Kendala / Tidak Ada Diatas,4,Tidak Ada Keluhan / Tidak Ada Diatas,4
110,Universitas Internasional Batam,Non Computing & Non Engineering,4,4,Tidak Ada Keluhan / Tidak Ada Diatas,Tidak Ada Kendala / Tidak Ada Diatas,4,Tidak Ada Keluhan / Tidak Ada Diatas,4
111,Universitas Internasional Batam,Computing & Engineering,4,5,Tidak Ada Keluhan / Tidak Ada Diatas,Tidak Ada Kendala / Tidak Ada Diatas,4,Bosan,4
112,Universitas Internasional Batam,Computing & Engineering,4,4,Tidak Ada Keluhan / Tidak Ada Diatas,Tidak Ada Kendala / Tidak Ada Diatas,4,Tidak Ada Keluhan / Tidak Ada Diatas,4

## Data Preprocessing

In [3]:
from sklearn import preprocessing
def label_array(array) :
    encoder = preprocessing.LabelEncoder()
    encoder.fit(array.unique())
    encoded_value = encoder.transform(array)
    return encoded_value

In [4]:
X1 = pd.DataFrame({"":label_array(df['Universitas'],)})
X2 = pd.DataFrame({"":label_array(df['Jenis Program Studi'],)})
X3 = pd.DataFrame({"":label_array(df['Keluhan Fisik Selama Pembelajaran Online'],)})
X4 = pd.DataFrame({"":label_array(df['Kendala Selama Pembelajaran Online'],)})
X5 = pd.DataFrame({"":label_array(df['Keluhan Psikis Selama Pembelajaran Online'],)})

print(X1.to_string(index=False, header=False))
print("\n")
print(X2.to_string(index=False, header=False))
print("\n")
print(X3.to_string(index=False, header=False))
print("\n")
print(X4.to_string(index=False, header=False))
print("\n")
print(X5.to_string(index=False, header=False))

2
2
1
4
3
2
2
0
1
4
2
2
2
2
1
3
2
3
2
3
2
2
3
0
2
3
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
3
3
3
3
3
3
3
3
3
3
2
2
2
3
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
4
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2


1
0
0
0
0
0
1
0
0
1
1
0
0
1
1
1
1
1
0
0
0
1
1
0
1
1
0
1
1
1
1
1
1
1
1
1
1
0
1
1
0
1
1
1
0
1
1
1
1
1
1
1
0
1
1
1
0
1
1
0
0
1
0
1
0
1
1
1
1
1
1
1
1
1
1
1
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0
1
0
0


14
19
 0
 9
16
12
 1
19
 3
 6
 5
14
19
19
20
 1
19
20
19
17
18
 4
19
 1
 1
19
 8
 2
14
10
 1
 0
10
 1
 1
19
 4
19
20
19
19
19
19
19
19
14
19
19
19
19
19
19
19
19
19
10
 1
19
10
19
19
 1
 1
 1
17
19
 1
19
19
19
19
19
19
19
19
19
 7
 0
13
11
19
15
19
19
 1
14
19
19
19
19
14
19
19
19
19
19
19
19
19
19
19
19
19
19
19
19
 1
19
19
19
19
19
19


7
7
7
0
3
5
2
7
3
2
0
2
7
7
7
0
4
3
4
6
4
0
7
7
0
7
7
0
1
7
0
0
7
0
7
7
0
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
0
7
7
7
0
7
7
7
0
7
7
7
7
7
7
7
7
0
7
7
0
7
1
7
7
0
7
7
7
0
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7
7


 6
15
14
 4
 8
10
 8
 4
10
 5
 0
 3
15
15
 0
15
15
 8
15
 7
 8
 0
15
13
 0
15
 0
 0
 1
11
 0
 0
11
 2
15
15
 2
15
15
15
15
15
15
15
15
15
15
12
11
15
15
11
15
15
15
 1
15
 0
11
15
 0
15
15
11
 0
11
15
15
15
15
15
15
11
 0
15
15
 0
15
 9
 0
15
 0
11
15
15
15
15
15
15
15
15
15
11
15
15
11
15
15
 1
15
 1
15
15
15
15
15
15
15
15
15
15
 0
15

In [5]:
y = df['Kepuasan Terhadap Pembelajaran Online']
print(y.to_string(index=False, header=False))

3
4
1
3
2
3
4
1
4
2
4
4
5
5
4
4
5
5
5
5
5
4
5
4
3
4
3
3
2
2
4
3
2
3
3
3
3
3
4
4
5
4
3
3
3
3
3
3
3
3
3
3
3
3
3
2
3
3
3
3
3
5
3
5
4
3
4
4
4
3
3
3
5
5
4
4
3
4
3
3
5
3
3
3
3
5
5
4
5
4
4
5
4
5
4
4
5
5
5
5
5
5
5
5
4
4
4
5
5
4
4
4
4

In [17]:
pp_df = pd.concat([X1, X2, X3, X4, X5], axis=1)
pp_df.columns = ['Universitas', 'Jenis Program Studi', 'Keluhan Fisik Selama Pembelajaran Online', 'Kendala Selama Pembelajaran Online', 'Keluhan Psikis Selama Pembelajaran Online']
pp_df.insert(0, "Model", "Random Forest Classifier")
pp_df = pp_df.drop('Model', axis=1)
pp_df

,Universitas,Jenis Program Studi,Keluhan Fisik Selama Pembelajaran Online,Kendala Selama Pembelajaran Online,Keluhan Psikis Selama Pembelajaran Online
0,2,1,14,7,6
1,2,0,19,7,15
2,1,0,0,7,14
3,4,0,9,0,4
4,3,0,16,3,8
...,...,...,...,...,...
108,2,1,19,7,15
109,2,0,19,7,15
110,2,1,19,7,15
111,2,0,19,7,0
112,2,0,19,7,15

In [18]:
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(pp_df, y, test_size=0.5, random_state=100)

In [19]:
X_train

,Universitas,Jenis Program Studi,Keluhan Fisik Selama Pembelajaran Online,Kendala Selama Pembelajaran Online,Keluhan Psikis Selama Pembelajaran Online
0,2,1,14,7,6
18,2,0,19,4,15
44,3,0,19,7,15
38,2,1,20,7,15
45,3,1,14,7,15
39,2,1,19,7,15
77,2,0,0,7,15
106,2,1,1,7,15
30,2,1,1,0,0
56,3,0,1,0,15
88,2,1,19,7,15
101,2,1,19,7,15
63,2,1,1,7,11
19,3,0,17,6,7
89,2,1,19,7,15
71,2,1,19,7,15
55,2,1,10,7,1
99,2,1,19,7,15
61,2,1,1,7,15
65,2,1,19,7,11
47,3,1,19,7,12
49,3,1,19,7,15
7,0,0,19,7,4
110,2,1,19,7,15
59,2,0,19,7,15
108,2,1,19,7,15
83,2,1,19,7,15
13,2,1,19,7,15
1,2,0,19,7,15
31,2,1,0,0,0
4,3,0,16,3,8
27,2,1,2,0,0
2,1,0,0,7,14
86,2,1,19,7,15
9,4,1,6,2,5
16,2,1,19,4,15
58,2,1,10,7,11
60,2,0,19,0,0
15,3,1,1,0,15
111,2,0,19,7,0
34,2,1,1,7,15
14,1,1,20,7,0
102,2,1,19,7,15
66,2,1,1,7,15
53,2,1,19,7,15
98,2,1,19,7,1
52,3,0,19,7,15
94,2,1,19,7,15
10,2,1,5,0,0
48,3,1,19,7,11
79,2,0,11,7,0
87,2,1,19,7,15
103,2,1,19,7,15
67,2,1,19,7,15
24,2,1,1,0,0
8,1,0,3,3,10

In [20]:
X_test
y_train

0      3
18     5
44     3
38     4
45     3
39     4
77     4
106    4
30     4
56     3
88     5
101    5
63     5
19     5
89     4
71     3
55     2
99     5
61     5
65     3
47     3
49     3
7      1
110    4
59     3
108    5
83     3
13     5
1      4
31     3
4      2
27     3
2      1
86     5
9      2
16     5
58     3
60     3
15     4
111    4
34     3
14     4
102    5
66     4
53     3
98     5
52     3
94     4
10     4
48     3
79     3
87     4
103    5
67     4
24     3
8      4
Name: Kepuasan Terhadap Pembelajaran Online, dtype: int64

# Modeling

### Random Forest Classifier

In [21]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(X_train, y_train)

RandomForestClassifier()

## Training the model

In [22]:
y_rfc_train_pred = rfc.predict(X_train)
y_rfc_test_pred = rfc.predict(X_test)

In [23]:
y_rfc_train_pred

array([3, 5, 3, 4, 3, 5, 4, 4, 3, 3, 5, 5, 5, 5, 5, 5, 2, 5, 4, 3, 3, 3,
       1, 5, 4, 5, 5, 5, 4, 3, 2, 3, 1, 5, 2, 5, 3, 3, 4, 4, 4, 4, 5, 4,
       5, 5, 3, 5, 4, 3, 3, 5, 5, 5, 3, 4], dtype=int64)

In [24]:
y_rfc_test_pred

array([3, 3, 4, 3, 3, 3, 3, 5, 5, 3, 5, 2, 5, 3, 5, 5, 3, 3, 3, 4, 5, 3,
       3, 2, 3, 3, 5, 5, 3, 4, 3, 1, 5, 3, 5, 4, 4, 2, 4, 3, 4, 5, 5, 3,
       4, 4, 3, 4, 3, 3, 4, 4, 3, 5, 5, 5, 5], dtype=int64)

## Evaluasi Model

In [25]:
#Input Model
from sklearn.metrics import accuracy_score, precision_score

rfc_train_accuracy = accuracy_score(y_train, y_rfc_train_pred)
rfc_test_accuracy = accuracy_score(y_test, y_rfc_test_pred)

rfc_train_precision = precision_score(y_train, y_rfc_train_pred, average='weighted', zero_division=0)
rfc_test_precision = precision_score(y_test, y_rfc_test_pred, average='weighted', zero_division=0)

print('Train Accuracy:', rfc_train_accuracy)
print('Test Accuracy:', rfc_test_accuracy)
print('Train Precision:', rfc_train_precision)
print('Test Precision:', rfc_test_precision)

Train Accuracy: 0.7678571428571429
Test Accuracy: 0.38596491228070173
Train Precision: 0.8053508991008992
Test Precision: 0.38467492260061914

In [26]:
rfc_result = pd.DataFrame(('Random Forest Classifier', rfc_train_accuracy, rfc_test_accuracy, rfc_train_precision, rfc_test_precision)).transpose()
rfc_result.columns = ['Model', 'Accuracy Train', 'Accuracy Test', 'Precision Train', 'Precision Test']
rfc_result

,Model,Accuracy Train,Accuracy Test,Precision Train,Precision Test
0,Random Forest Classifier,0.767857,0.385965,0.805351,0.384675

## Save the trained model

In [27]:
import sklearn
import joblib

scikit_ver = sklearn.__version__
print(scikit_ver)

joblib.dump(rfc,"RFC_113(1.0.2).pkl")

1.0.2

['RFC_113(1.0.2).pkl']

## Load the saved model

In [ ]:
RandomForest = joblib.load('RFC_113(1.0.2).pkl')

In [ ]:
predictions = rfc.predict(X_test)

In [30]:
X_test.shape

(57, 5)

In [31]:
X_test.shape

(57, 5)